/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dbarboza' at '8/19/15 12:54 PM' with Gradle 2.6
 *
 * @author dbarboza, @date 8/19/15 12:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
